@ECommerce.web_HostAddress = https://localhost:7045

Get {{ECommerce.web_HostAddress}}/api/Products?sort=5
Accept: application/json
###
Get {{ECommerce.web_HostAddress}}/api/Products/19
Accept: application/json
###
Get {{ECommerce.web_HostAddress}}/api/Products/Brands
Accept: application/json
###
Get {{ECommerce.web_HostAddress}}/api/Products/Types
Accept: application/json
###